name: Build Docker images

on:
 push:
  branches: ["main"]

jobs:
 build-and-push-dockerfile-image:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout repository
     uses: actions/checkout@v4
   - name: Set up Docker Buildx
     uses: docker/setup-buildx-action@v3

   - name: Log in to Docker Hub
     uses: docker/login-action@v3
     with:
      registry: docker.io
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}

   - name: Extract metadata
     id: meta
     uses: docker/metadata-action@v5
     with:
      images: ${{ secrets.DOCKERHUB_USERNAME }}/rac-hurlingham-cms
      tags: |
       type=ref,event=branch
       type=sha,format=short,prefix=
       type=raw,value=latest,enable={{is_default_branch}}

   - name: Build and push Docker image
     uses: docker/build-push-action@v6
     with:
      context: ./rac-hurlingham-cms
      push: true
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
      cache-from: type=gha
      cache-to: type=gha,mode=max
